export const CONFIG_READ_KEYS = [
  "STATION_DATABASE_URL",
  "PACK_DATABASE_URL",
  "STATION_MASTER_KEY",
  "STATION_CONTROL_TOKEN",
  "STATION_COCKPIT_PASSWORD",
  "STATION_COCKPIT_PORT",
  "STATION_WORKER_PORT",
  "NODE_ENV",
  "STATION_GRAPH_TENANT_ID",
  "STATION_GRAPH_CLIENT_ID",
  "STATION_GRAPH_CLIENT_SECRET",
] as const;

export type ConfigKey = (typeof CONFIG_READ_KEYS)[number];
